### ISSUE TITLE
page transition on dark theme flashes white

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/drips-app-v2#557] opened 2023-07-12 08:35 UTC
also weird gradient in splits list flashes but I guess wouldn't if the white flash goes away

Uploading Screen Recording 2023-07-12 at 10.33.39.mov…

**Comment by evvvritt** [comment] 2023-07-12 08:35
(we should set bg on <html> element ?)

**Comment by evvvritt** [comment] 2023-07-12 08:53
https://github.com/radicle-dev/drips-app-v2/assets/6071219/b98ee9e2-e5bd-4076-b875-297289393bd6

**Comment by efstajas** [comment] 2023-07-13 20:29
i can't reproduce it somehow. this does happen on first load, but when navigating within the app, I don't get that white flash

**Comment by efstajas** [comment] 2023-07-26 09:30
closing for now since I can't repro, feel free to re-open if it remains a problem! can also jump in a call to check what's going on exactly 👍

**Closed by efstajas** 2023-07-26 09:30 UTC
