### ISSUE TITLE
not possible to switch between different wallets in Metamask

### ISSUE THREAD

**Issue by xmxanuel** [radicle-dev/drips-app-v2#559] opened 2023-07-12 08:45 UTC
**Problem**
- It is not possible to switch the wallet address easily
- I connected `Wallet A` yesterday, today I want to use `Wallet B` 
- I clicked disconnect and connect new wallet but `Wallet A` gets automatically pre-selected

**Comment by efstajas** [comment] 2023-07-12 09:04
@xmxanuel are you on the newest version of metamask, the one that looks like this:

<img width="423" alt="Screenshot 2023-07-12 at 11 04 05" src="https://github.com/radicle-dev/drips-app-v2/assets/1018218/992679e0-5be9-4d2a-b48b-acfc97c461a2">

?

When I click the account dropdown in metamask and switch to a different connected account, the app reloads and applies the newly-selected address 🤔

**Comment by efstajas** [comment] 2023-07-26 09:28
yo @xmxanuel since I can't reproduce it, i'm gonna close it for now. Feel free to re-open if it's still an issue!

**Closed by efstajas** 2023-07-26 09:28 UTC

**Comment by xmxanuel** [comment] 2023-07-26 09:45
I tried to reproduce it again on https://www.drips.network/. 

It seems to work now. :+1:
